version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3000:3000'
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/xxx/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: xxx
      MYSQL_ROOT_PASSWORD: xxx
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/xxx/aaa:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
